### ISSUE TITLE
Table Schema UI: labels for the rows are not in line with the actual rows

### ISSUE THREAD

**Issue by Daniellappv** [datopian/datapub#59]
The labels for the rows are not in line with the actual rows, e.g. type and format are on the same row, see

![image](https://user-images.githubusercontent.com/45828069/95345078-0aeed000-08c3-11eb-98ea-d27ac27fa156.png)

(Bootstrap 3.3.7)

## Acceptance

* [ ] Labels for rows (title, description, type, format) are in line with the actual rows

## Task-list

TBA

**Comment by mariorodeghiero** [comment]
FIXED. Tested in `ckan-blob-storage` in the print below.

![Screenshot from 2020-10-08 14-25-19](https://user-images.githubusercontent.com/24671133/95508966-312b7300-098a-11eb-8420-5ee41ce3bc42.png)

**Comment by mbeilin** [comment]
@mariorodeghiero still not looking good enough in NHS:
![Screenshot from 2020-10-11 10-48-19](https://user-images.githubusercontent.com/61929774/95716268-da68b680-0c73-11eb-98d1-0504584fa9d2.png)

**Comment by mbeilin** [comment]
FIXED in NHS also.
![Screenshot from 2020-10-12 18-31-45](https://user-images.githubusercontent.com/61929774/95764636-66510180-0cb9-11eb-8367-b26cf41ab6bd.png)
